---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 name: php
 namespace: default
spec:
 scaleTargetRef:
   kind: Deployment
   name: php-apache
   apiVersion: apps/v1
 minReplicaCount: 1
 maxReplicaCount: 5
 cooldownPeriod: 20
 pollingInterval: 10
 triggers:
 - type: prometheus
   metadata:
     serverAddress: http://prom-prometheus-server.prom.svc.cluster.local
     metricName: traefix_requests
     query: |
       sum(rate(traefik_service_requests_total{code="200"}[1m]))
     threshold: "2.0"
 advanced:
   horizontalPodAutoscalerConfig:
     behavior:
       scaleDown:
         stabilizationWindowSeconds: 60 # Keep desired states from the past 1 min 
         policies:
           # 100% replicas can be removed
           - type: Percent
             value: 100
             periodSeconds: 10
         selectPolicy: Max # choose the policy that affects the max number of pods
