apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: simpleapp
    count: 1
  - name: simpleapp-canary
    count: 1

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: simpleapp
      spec:
        template:
          spec:
            containers:
              - name: simpleapp
                image: tvminh/simpleapp:production

