apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
        - name: simpleapp
          imagePullPolicy: Always
          image: tvminh/simpleapp:latest
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: reload-cm
