apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: cert-manager
spec:
  method: kubernetes
  mount: demo-auth-mount
  kubernetes:
    role: cloudflare
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-cloudflare
  namespace: cert-manager
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: cloudflare/config

  # dest k8s secret
  destination:
    name: cloudflare-key-vault
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
