apiVersion: v1
kind: ServiceAccount
metadata: 
  name: internal-app
  namespace: dev 
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  annotations:
    kubernetes.io/service-account.name: vault
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: internal-app
    namespace: dev
---
### Create Vault External service to work with Istio
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: vault-service-entry
spec:
  hosts:
    - vault.vault.svc.cluster.local
  ports:
    - number: 8200
      name: http
      protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS