apiVersion: v1
kind: ServiceAccount
metadata: 
  name: internal-app
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault
  namespace: default
  labels:
    "app.kubernetes.io/name": vault
rules:
  - apiGroups: ["apps", "", "rbac.authorization.k8s.io"]
    resources: ["deployments", "pods", "serviceaccounts", "serviceaccounts/token", "roles", "rolebindings"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault
subjects:
  - kind: ServiceAccount
    name: internal-app
    namespace: default
  - kind: ServiceAccount
    name: vault
    namespace: default
